# Generated by Django 5.2.4 on 2025-07-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSCREAM', '0004_remove_flavorproposal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavorproposal',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='flavorproposal',
            name='flavor_name',
        ),
        migrations.RemoveField(
            model_name='flavorproposal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='flavorproposal',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavorproposal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flavorproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icecreams', to='iSCREAM.vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iSCREAM.icecream'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iSCREAM.icecream'),
        ),
        migrations.DeleteModel(
            name='IceCreamProduct',
        ),
    ]
