# Generated by Django 5.2.4 on 2025-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSCREAM', '0005_remove_flavorproposal_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavorproposal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proposed_flavors/'),
        ),
    ]
