# Generated by Django 5.2.4 on 2025-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSCREAM', '0007_alter_flavorproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavorproposal',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavorproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
