# Generated by Django 5.2.4 on 2025-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSCREAM', '0008_flavorproposal_stock_alter_flavorproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proposed_flavors/'),
        ),
    ]
