# Generated by Django 5.2.4 on 2025-07-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSCREAM', '0009_icecream_description_icecream_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorproposal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iSCREAM.vendor'),
        ),
    ]
