# Generated by Django 5.2.4 on 2025-07-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iSCREAM', '0010_alter_flavorproposal_vendor'),
        ('iSCREAM', '0011_auto_20250717_1716'),
    ]

    operations = [
    ]
